### PR TITLE
rearrange contents in dist-train.md

### PR DESCRIPTION
**Pull request by nudles**
@chrishkchris  pls review and test.

In addition, the some APIs can be improved
1. [backward_and_spars_update](https://github.com/apache/singa/blob/master/python/singa/opt.py#L458)  --> `backward_and_sparse_update`
2. [train_mnist_cnn()](https://github.com/apache/singa/blob/master/examples/autograd/mnist_cnn.py#L138) -->
```python
train_mnist_cnn( gpu_num=1, gpu_per_node=1, nccl_id=None):
```
all other variables can be created and set inside `train_mnist_cnn` to make the API simple to call.

### CODE REVIEW

**Comment by chrishkchris** [comment]
thanks, I will review and test

**Comment by nudles** [comment]
The [DIST](https://github.com/apache/singa/blob/master/examples/autograd/mnist_cnn.py#L153) variable can be inferred based on the num of gpus?
for MPI, you do not need to pass `num_gpus` explicitly to `DistOpt`? but for multiprocessing, you need?

The format of the docString is very good!
Some arguments may need more explanations:
1. [nccl_id] (https://github.com/apache/singa/blob/master/python/singa/opt.py#L191) is compulsory for multiprocessing? and should be none for MPI?
2. how about num_gpu and gpu_per_node?
3. give a concrete example for `rank_in_local` and `rank_in_global`

In addition, we may need to introduce the implementation of distributed training code in SINGA at the end of this documentation. We have given the overview of  the synchronous training algorithm at the beginning in this documentation. But how what is done at the Python side and C++ side is unknown. When NCCL and MPI APIs are called. This part is mainly for developers (not for end users).

**Comment by chrishkchris** [comment]
> The [DIST](https://github.com/apache/singa/blob/master/examples/autograd/mnist_cnn.py#L153) variable can be inferred based on the num of gpus?

For MPI, I do not give the num of gpus (see the answer in the next question), so DIST variable cannot be inferred in the case of MPI 

> for MPI, you do not need to pass `num_gpus` explicitly to `DistOpt`? but for multiprocessing, you need?

For MPI, do not need to pass num_gpus, because this information is obtained from MPI   
https://github.com/apache/singa/blob/dev/src/io/communicator.cc#L81
`MPI_Comm_size(MPI_COMM_WORLD, &totalMPIRanksInGlobal)`
However, multiprocess do not has this information, so we need to pass the num_gpus to let the communicator knows

> 
> The format of the docString is very good!
> Some arguments may need more explanations:
> 
> 1. [nccl_id] (https://github.com/apache/singa/blob/master/python/singa/opt.py#L191) is compulsory for multiprocessing? and should be none for MPI?
> 2. how about num_gpu and gpu_per_node?
> 3. give a concrete example for `rank_in_local` and `rank_in_global`

Yes, I will explain them in the docs.
1. nccl_id is complusory for the initialization of nccl communicator in both MPI and multiprocess in our code, here is the place which needs the id
https://github.com/apache/singa/blob/dev/src/io/communicator.cc#L108
`ncclCommInitRank(&comm, totalMPIRanksInGlobal, id, MPIRankInGlobal));`
2. num_gpu and gpu_per_node is required by multiprocess, but MPI does not need it because it is provided by mpich function: 
https://github.com/apache/singa/blob/dev/src/io/communicator.cc#L81
3. rank_in_local is the rank within the same node, rank_in_global is the rank in all the nodes

> In addition, we may need to introduce the implementation of distributed training code in SINGA at the end of this documentation. We have given the overview of the synchronous training algorithm at the beginning in this documentation. But how what is done at the Python side and C++ side is unknown. When NCCL and MPI APIs are called. This part is mainly for developers (not for end users).

got it, thanks. Will explain the implementation

**Comment by nudles** [comment]
Is nccl_id passed to `train_mnist_cnn` for training with MPI?
For multiprocessing, num_gpu = gpu_per_node, hence we only need num_gpu?

**Comment by chrishkchris** [comment]
> Is nccl_id passed to `train_mnist_cnn` for training with MPI?
No, in the case of MPI, nccl_id is generated and immediately broadcasted by MPI from rank0 to every rank.  
https://github.com/apache/singa/blob/master/src/io/communicator.cc#L102 
```
  if (MPIRankInGlobal == 0) ncclGetUniqueId(&id);
  MPICHECK(MPI_Bcast((void *)&id, sizeof(id), MPI_BYTE, 0, MPI_COMM_WORLD));
```

> For multiprocessing, num_gpu = gpu_per_node, hence we only need num_gpu?

 This is reserve for future use, because previously I planned using socket to broadcast ncclid instead of MPI

**Comment by chrishkchris** [comment]
> @chrishkchris pls review and test.
> 
> In addition, the some APIs can be improved
> 
> 1. [backward_and_spars_update](https://github.com/apache/singa/blob/master/python/singa/opt.py#L458)  --> `backward_and_sparse_update`
> 2. [train_mnist_cnn()](https://github.com/apache/singa/blob/master/examples/autograd/mnist_cnn.py#L138) -->
> 
> ```python
> train_mnist_cnn( gpu_num=1, gpu_per_node=1, nccl_id=None):
> ```
> 
> all other variables can be created and set inside `train_mnist_cnn` to make the API simple to call.

I am reducing the number of arguments in train_mnist_cnn

**Comment by chrishkchris** [comment]
I will also provide a doc_dist_train.py specially for this demo example

**Comment by nudles** [comment]
Then would it be better to design the APIs in this way:
1. For training with MPI
```python
 # in mnist_mpi.py
if __name__  == '__main__':
  sgd = ...
  sgd = DistOpt(sgd)
  train_mnist(sgd, sparse, topK)
```

2. For training via multiprocessing
```python
 # in mnist_multiprocessing.py
if __name__  == '__main__':
  nccl_id = ...
  sgd = ...
  sgd = DistOpt(sgd, num_gpu, nccl_id)
  train_mnist(sgd, sparse, topK)
```

Even if you use socket, multiprocessing can only run on a single node, hence num_gpu = gpu_per_node.

**Comment by chrishkchris** [comment]
> Then would it be better to design the APIs in this way:
> 
> 1. For training with MPI
> 
> ```python
>  # in mnist_mpi.py
> if __name__  == '__main__':
>   sgd = ...
>   sgd = DistOpt(sgd)
>   train_mnist(sgd, sparse, topK)
> ```
> 
> 1. For training via multiprocessing
> 
> ```python
>  # in mnist_multiprocessing.py
> if __name__  == '__main__':
>   nccl_id = ...
>   sgd = ...
>   sgd = DistOpt(sgd, num_gpu, nccl_id)
>   train_mnist(sgd, sparse, topK)
> ```
> 
> Even if you use socket, multiprocessing can only run on a single node, hence num_gpu = gpu_per_node.

sorry, Distopt cannot passed into the multiprocess, this is because DistOpt has the communicator initialized, if we pass it into multiprocess the same object will be replicated. The code cannot run

**Comment by chrishkchris** [comment]
> Then would it be better to design the APIs in this way:
> 
> 1. For training with MPI
> 
> ```python
>  # in mnist_mpi.py
> if __name__  == '__main__':
>   sgd = ...
>   sgd = DistOpt(sgd)
>   train_mnist(sgd, sparse, topK)
> ```
> 
> 1. For training via multiprocessing
> 
> ```python
>  # in mnist_multiprocessing.py
> if __name__  == '__main__':
>   nccl_id = ...
>   sgd = ...
>   sgd = DistOpt(sgd, num_gpu, nccl_id)
>   train_mnist(sgd, sparse, topK)
> ```
> 
> Even if you use socket, multiprocessing can only run on a single node, hence num_gpu = gpu_per_node.

Sorry, I updated my comment
num_gpu is the local rank of a specific process
gpu_per_node is the total number of ranks in a single node

**Comment by chrishkchris** [comment]
I have submitted a PR concerning the change of APIs in example,
and also added the two specific examples for the dist-train.md documentation
https://github.com/apache/singa/pull/651

**Pull request merged**
